config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  resources :users, only: :show
  resources :posts do
    post 'favorite/:id' => 'favorites#create', as: 'create_favorite'
    delete 'favorite/:id' => 'favorites#destroy', as: 'destroy_favorite'
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
belongs_to :user
has_one_attached :image
has_many :favorites, dependent: :destroy 
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

validates :name, presence: true
validates :profile, presence: true
has_many :posts
has_many :favorites

def favorite_find(post_id)
  favorites.where(post_id: post_id).exists?
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:profile])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_post
  before_action :authenticate_user!  

  def create
    if @post.user_id != current_user.id   
      @favorite = Favorite.create(user_id: current_user.id, post_id: @post.id)
      redirect_to root_path    
    end
  end
  
  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, post_id: @post.id)
    @favorite.destroy
    redirect_to root_path
  end

  private
  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!,except: [:index,:show]
  before_action :set_post, only: [:show, :edit,:update,:destroy]
  before_action :move_to_index, except: [:index, :show ,:new, :create]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show

  end

  def update
    if @post.update(post_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to action: :index
    else
      render :new
   end
  end

  def destroy
    if @post.destroy
      redirect_to action: :index
    end
  end

  private

  def post_params
    params.require(:post).permit(:headwear,:tops,:shoes,:accessories,:bottoms,:outer,:image,:name).merge(user_id: current_user.id)
  end

  def move_to_index
    unless current_user.id == @post.user_id 
      redirect_to action: :index
    end
  end

  def set_post
    @post = Post.find(params[:id])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  @user = User.find(params[:id])
  @name = @user.name
  @profile = @user.profile
  @posts = @user.posts

  favorites = Favorite.where(user_id: current_user.id).pluck(:post_id) 
  @favorite_list = Post.find(favorites)

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Lookat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
<header class="header">
    <div class="header__bar row">
      <h1 class="grid-6"><a href="/">LOOK AT</a></h1>
      <% if user_signed_in? %>
        <div class="user_nav grid-6">
          <span><%= current_user.name %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
          <%= link_to "投稿する", new_post_path, class: "post" %>
        </div>
      <% else %>
        <div class="grid-6">
          <%= link_to "ログイン", new_user_session_path, class: "post" %>
          <%= link_to "新規登録", new_user_registration_path, class: "post" %>
        </div>
      <% end %>
    </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © Lookat All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f|%>

  <div class="field">
    <%= f.label :image,"Photo" %>
    <%= f.file_field :image, id:"post_image" %>
  </div>

  <div class="field">
    <%= f.label :headwear, "Headwear" %>
    <%= f.text_field :headwear, id:"post_headwear" %>
  </div>

  <div class="field">
    <%= f.label :tops, "Tops" %>
    <%= f.text_field :tops, id:"post_tops" %>
  </div>

    <div class="field">
    <%= f.label :outer, "Outer" %>
    <%= f.text_field :outer, id:"post_outer" %>
  </div>

    <div class="field">
    <%= f.label :bottoms, "Bottoms" %>
    <%= f.text_field :bottoms, id:"post_bottoms" %>
  </div> 

   <div class="field">
    <%= f.label :shoes, "Shoes" %>
    <%= f.text_field :shoes, id:"post_shoes" %>
  </div>

    <div class="field">
    <%= f.label :accessories, "Acessories" %>
    <%= f.text_field :accessories, id:"post_accessories" %>
  </div>

  <div class="actions">
    <%= f.submit "保存する", class: :form__btn  %>
  </div>

<% end %>

app/views/posts/_prototype.html.erb
<div class="card">
  <%= link_to image_tag("プロトタイプの画像", class: :card__img ), root_path%>
  <div class="card__body">
    <%= link_to "プロトタイプのタイトル", root_path, class: :card__title%>
    <p class="card__summary">
      <%= "プロトタイプのキャッチコピー" %>
    </p>
    <%= link_to "by プロトタイプの投稿者名", root_path, class: :card__user %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="contents row">
  <div class="container">
 <h2 class="page-heading">プロトタイプ編集</h2>
    <%= render partial: "form", locals: { post: @post } %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="contents row">
  <% @posts.each do |post| %>
    <div class="content_post">
     <%= link_to image_tag(post.image, size: '500x500'), post_path(post.id), method: :get %>
      <span class="name">
        <%= post.user.name %>
      </span>
    </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>      
    <%= render partial: "form", locals: { post: @post } %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="contents row">
  <div class="content_post_show">
  <%= link_to image_tag(@post.image,size: '500x500'), post_path(@post.id), method: :get %>
    <% if user_signed_in? && current_user.id == @post.user_id %>
      <div class="more">
        <span><%= image_tag 'arrow_top.png' %></span>
        <ul class="more_list">
          <li>
            <%= link_to '編集', edit_post_path(@post.id), method: :get %>
          </li>
          <li>
            <%= link_to '削除', post_path(@post.id), method: :delete %>
          </li>
        </ul>
      </div>
    <% end %>
    <span class="name_show">
      <a href="/users/<%= @post.user.id %>">
        <%= @post.user.name %>
      </a>
    </span>
  </div>
   <table class="coordinate-item">
      <tbody>
        <tr>
          <th class="detail-item">Headwear</th>
          <td class="detail-value"><%= @post.headwear %></td>
        </tr>
        <tr>
          <th class="detail-item">Tops</th>
          <td class="detail-value"><%= @post.tops %></td>
        </tr>
        <tr>
          <th class="detail-item">Outer</th>
          <td class="detail-value"><%= @post.outer %></td>
        </tr>
        <tr>
          <th class="detail-item">Bottoms</th>
          <td class="detail-value"> <%= @post.bottoms %></td>
        </tr>
        <tr>
          <th class="detail-item">Shoes</th>
          <td class="detail-value"><%= @post.shoes %></td>
        </tr>
        <tr>
          <th class="detail-item">Accessories</th>
          <td class="detail-value"><%= @post.accessories %></td>
        </tr>
      </tbody>
    </table>
        <div class="option">
      <div class="favorite-btn">
      <% if user_signed_in? && current_user != @post.user %>
    <% if current_user.favorite_find(@post.id) %>
      <%= link_to 'お気に入りからはずす', post_destroy_favorite_path(@post.id), method: :delete %>
    <% else %>
      <%= link_to 'お気に入り登録する', post_create_favorite_path(@post.id), method: :post %>
    <% end %>
  <% end %>
  </div>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">ニックネーム</th>
            <td class="table__col2"><%= @user.name %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2_profile"><%= @user.profile %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "POST"%>
      </h2>
      <div class="user__card_user_show">
       <% @posts.each do |post| %>
    <div class="content_post_user_show">
     <%= link_to image_tag(post.image, size: '400x400'), post_path(post.id), method: :get %>
    </div>
  <% end %>
  </div>
 <h2 class="page-heading">
 <%= "お気に入りの投稿"%>
</h2>
<% if @favorite_list.present? %>
<div class="user__card_favorite">
  <% @favorite_list.each do |post| %>
  <div class="user__post_favorite">
    <%= link_to image_tag(post.image, size: '300x300'), post_path(post.id), method: :get %>
 </div>
<% end %>
<% end %>
      </div>

    </div>
  </div>
</div>